main.name = "codipwn" 
main.plugins.bt-tether.devices.android-phone.enabled = true 
main.plugins.bt-tether.devices.android-phone.interval = 1 
main.plugins.bt-tether.devices.android-phone.ip = "192.168.44.44" 
main.plugins.bt-tether.devices.android-phone.mac = "" # TODO: Add your phone MAC address here
main.plugins.bt-tether.devices.android-phone.max_tries = 0 
main.plugins.bt-tether.devices.android-phone.netmask = 14 
main.plugins.bt-tether.devices.android-phone.priority = 1 
main.plugins.bt-tether.devices.android-phone.scantime = 20 
main.plugins.bt-tether.devices.android-phone.search_order = 1 
main.plugins.bt-tether.devices.android-phone.share_internet = true 
main.plugins.bt-tether.enabled = true 
main.plugins.bt-tether.ip = "192.168.44.44" 
main.plugins.bt-tether.mac = "" # TODO: Add your phone MAC address here
main.plugins.bt-tether.phone = "Android" 
main.whitelist = [] 

main.plugins.bt-tether.phone-name = "" # TODO: Add your phone name here

main.plugins.auto-tune.enabled = true
main.plugins.auto-tune.extra_channels = 15
main.plugins.auto-tune.reset_history = true
main.plugins.auto-tune.show_hidden = false

main.plugins.auto-update.enabled = false
main.plugins.auto-update.install = true
main.plugins.auto-update.interval = 1

main.plugins.fix_services.enabled = true

main.plugins.gdrivesync.backup_folder = "PwnagotchiBackups"
main.plugins.gdrivesync.backupfiles = [""]
main.plugins.gdrivesync.enabled = false

main.plugins.gpio_buttons.enabled = false

main.plugins.gps.device = "/dev/ttyUSB0"
main.plugins.gps.enabled = false
main.plugins.gps.speed = 19200

main.plugins.gps_listener.enabled = false

main.plugins.grid.enabled = false
main.plugins.grid.report = true

main.plugins.logtail.enabled = true
main.plugins.logtail.max-lines = 10000

main.plugins.memtemp.enabled = false
main.plugins.memtemp.orientation = "horizontal"
main.plugins.memtemp.scale = "celsius"

main.plugins.ohcapi.api_key = "sk_your_api_key_here"
main.plugins.ohcapi.enabled = false
main.plugins.ohcapi.receive_email = "yes"

main.plugins.pwndroid.display = false
main.plugins.pwndroid.display_altitude = false
main.plugins.pwndroid.enabled = true

main.plugins.pisugarx.default_display = "percentage"
main.plugins.pisugarx.enabled = false
main.plugins.pisugarx.rotation = false

main.plugins.session-stats.enabled = true
main.plugins.session-stats.save_directory = "/var/tmp/pwnagotchi/sessions/"

main.plugins.ups_hat_c.bat_x_coord = 140
main.plugins.ups_hat_c.bat_y_coord = 0
main.plugins.ups_hat_c.enabled = false
main.plugins.ups_hat_c.label_on = true
main.plugins.ups_hat_c.shutdown = 5

main.plugins.ups_lite.enabled = false
main.plugins.ups_lite.shutdown = 2

main.plugins.webcfg.enabled = true

main.plugins.webgpsmap.enabled = true

main.plugins.wigle.api_key = ""
main.plugins.wigle.donate = false
main.plugins.wigle.enabled = false

main.plugins.wpa-sec.api_key = "" # TODO: Add your API key here
main.plugins.wpa-sec.api_url = "https://wpa-sec.stanev.org" 
main.plugins.wpa-sec.download_results = true 
main.plugins.wpa-sec.enabled = true 
main.plugins.wpa-sec.show_pwd = true 

main.plugins.internet-conection.enabled = false

main.plugins.internet-connection.enabled = true

main.plugins.memtemp-plus.enabled = true
main.plugins.memtemp-plus.fields = "mem,cpu,temp,freq"
main.plugins.memtemp-plus.linespacing = 10
main.plugins.memtemp-plus.orientation = "horizontal"
main.plugins.memtemp-plus.position = "165,85"
main.plugins.memtemp-plus.scale = "celsius"

main.plugins.hashie.enabled = false

main.plugins.handshakes-dl-hashie.enabled = true

main.plugins.hashieclean.enabled = true

main.plugins.instattack.enabled = false

main.plugins.agev2.enabled = false

main.plugins.expv2.bar_symbols_count = 8
main.plugins.expv2.enabled = true
main.plugins.expv2.exp_x_coord = 177
main.plugins.expv2.exp_y_coord = 73
main.plugins.expv2.lvl_x_coord = 145
main.plugins.expv2.lvl_y_coord = 73

main.plugins.enable_assoc.enabled = true
main.plugins.enable_assoc.position = "209,109,30,59"

main.plugins.enable_deauth.enabled = true
main.plugins.enable_deauth.position = "215,109,30,59"

main.plugins.wpa-sec-list.enabled = true

main.plugins.wof.enabled = true
main.plugins.wof.icon = true
main.plugins.wof.icon_reverse = false
main.plugins.wof.position.x = 5
main.plugins.wof.position.y = 82

main.plugins.wof.online_timespan = 30
main.plugins.wof.wof_file = "/root/Wall-of-Flippers/Flipper.json"

main.confd = "/etc/pwnagotchi/conf.d/"
main.custom_plugin_repos = [
  "https://github.com/jayofelony/pwnagotchi-torch-plugins/archive/master.zip",
  "https://github.com/Sniffleupagus/pwnagotchi_plugins/archive/master.zip",
  "https://github.com/NeonLightning/pwny/archive/master.zip",
  "https://github.com/marbasec/UPSLite_Plugin_1_3/archive/master.zip",
  "https://github.com/wpa-2/Pwnagotchi-Plugins/archive/master.zip",
  "https://github.com/evilsocket/pwnagotchi-plugins-contrib/archive/refs/heads/master.zip",
  "https://github.com/PwnPeter/pwnagotchi-plugins/archive/master.zip",
  "https://github.com/arturandre/pwnagotchi-beacon-plugins/archive/master.zip",
  "https://github.com/Sniffleupagus/pwnagotchi_plugins/archive/refs/heads/main.zip",
  "https://github.com/Kaska89/pwnagotchi-EXPv2-plugin/archive/refs/heads/main.zip",
  "https://github.com/dbukovac/pwnagotchi-plugins-contrib/archive/refs/heads/master.zip",
  "https://github.com/cyberartemio/wof-pwnagotchi-plugin/archive/refs/heads/main.zip",
]
main.custom_plugins = "/usr/local/share/pwnagotchi/custom-plugins/"
main.lang = "en"
main.plugin.gdrivesync.interval = 1

main.iface = "wlan0mon"
main.log.path = "/etc/pwnagotchi/log/pwnagotchi.log"
main.log.path-debug = "/etc/pwnagotchi/log/pwnagotchi-debug.log"
main.log.rotation.enabled = true
main.log.rotation.size = "10M"
main.mon_max_blind_epochs = 5
main.mon_start_cmd = "/usr/bin/monstart"
main.mon_stop_cmd = "/usr/bin/monstop"
main.no_restart = false

ui.display.enabled = false
ui.display.rotation = 180
ui.display.type = "waveshare_2"

ui.cursor = true
ui.font.name = "DejaVuSansMono"
ui.font.size_offset = 0
ui.fps = 0
ui.invert = true

ui.faces.angry = "(-_-')"
ui.faces.awake = "(◕‿‿◕)"
ui.faces.bored = "(-__-)"
ui.faces.broken = "(☓‿‿☓)"
ui.faces.cool = "(⌐■_■)"
ui.faces.debug = "(#__#)"
ui.faces.demotivated = "(≖__≖)"
ui.faces.excited = "(ᵔ◡◡ᵔ)"
ui.faces.friend = "(♥‿‿♥)"
ui.faces.grateful = "(^‿‿^)"
ui.faces.happy = "(•‿‿•)"
ui.faces.intense = "(°▃▃°)"
ui.faces.lonely = "(ب__ب)"
ui.faces.look_l = "(☉_☉ )"
ui.faces.look_l_happy = "(◕‿◕ )"
ui.faces.look_r = "( ⚆_⚆)"
ui.faces.look_r_happy = "( ◕‿◕)"
ui.faces.motivated = "(☼‿‿☼)"
ui.faces.png = false
ui.faces.position_x = 0
ui.faces.position_y = 34
ui.faces.sad = "(╥☁╥ )"
ui.faces.sleep = "(⇀‿‿↼)"
ui.faces.sleep2 = "(≖‿‿≖)"
ui.faces.smart = "(✜‿‿✜)"
ui.faces.upload = "(1__0)"
ui.faces.upload1 = "(1__1)"
ui.faces.upload2 = "(0__1)"

ui.web.address = "::"
ui.web.auth = false
ui.web.enabled = true
ui.web.on_frame = ""
ui.web.origin = ""
ui.web.password = "changeme"
ui.web.port = 8080
ui.web.username = "changeme"

personality.advertise = true
personality.ap_ttl = 120
personality.associate = true
personality.bond_encounters_factor = 20000
personality.bored_num_epochs = 15
personality.channels = [
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  9,
  10,
  11,
  12,
  13,
  9,
  10,
  8,
  6,
  3,
  1,
  7,
  2,
  13,
  4,
  12,
  11,
  5,
]
personality.deauth = true
personality.excited_num_epochs = 10
personality.hop_recon_time = 10
personality.max_inactive_scale = 2
personality.max_interactions = 3
personality.max_misses_for_recon = 5
personality.min_recon_time = 5
personality.min_rssi = -200
personality.recon_inactive_multiplier = 2
personality.recon_time = 30
personality.sad_num_epochs = 25
personality.sta_ttl = 300
personality.throttle_a = 0.4
personality.throttle_d = 0.9

bettercap.handshakes = "/home/pi/handshakes"
bettercap.silence = [
  "ble.device.new",
  "ble.device.lost",
  "ble.device.disconnected",
  "ble.device.connected",
  "ble.device.service.discovered",
  "ble.device.characteristic.discovered",
  "wifi.client.new",
  "wifi.client.lost",
  "wifi.client.probe",
  "wifi.ap.new",
  "wifi.ap.lost",
  "mod.started",
]

fs.memory.enabled = true
fs.memory.mounts.log.enabled = true
fs.memory.mounts.log.mount = "/etc/pwnagotchi/log/"
fs.memory.mounts.log.rsync = true
fs.memory.mounts.log.size = "50M"
fs.memory.mounts.log.sync = 60
fs.memory.mounts.log.zram = true

fs.memory.mounts.data.enabled = true
fs.memory.mounts.data.mount = "/var/tmp/pwnagotchi"
fs.memory.mounts.data.rsync = true
fs.memory.mounts.data.size = "10M"
fs.memory.mounts.data.sync = 3600
fs.memory.mounts.data.zram = true
